config/routes.rb
SalesListingApp::Application.routes.draw do

    resources :products
    resources :purchases
    resources :users
    resources :sessions

    root :to => 'pages#home'
    match 'purchases/:id' => 'purchases#create', :as => :buy
    match '/home', :to => 'pages#home'
    match '/about', :to => 'pages#about'
    match '/contact', :to => 'pages#contact'
    match '/privacy', :to => 'pages#privacy'
    match '/signup', :to => 'users#new'
    match '/login', :to => 'sessions#new'
    match '/logout', :to => 'sessions#destroy'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :available, :photo, :brand, :color, :description, :expiry_date, :fragile, :listing_date, :user_id, :name, :price

  mount_uploader :photo, PhotoUploader

  validates :brand, :color, :description, :expiry_date, :listing_date, :user_id, :name, :price, :presence => true

  belongs_to :user
  has_many :purchases

  KULER = [['Amber'], ['Aquamarine'], ['Auburn'], ['Beige'], ['Black'], ['Blue'], ['Bronze'], ['Brown'], ['Burgundy'], ['Crimson'], ['Cyan'], ['Emerald'], ['Fuchsia'], ['Gold'], ['Green'], ['Grey'], ['Indigo'], ['Ivory'], ['Jade'], ['Khaki'], ['Lavender'], ['Lemon'], ['Lilac'], ['Lime'], ['Magenta'], ['Maroon'], ['Mauve'], ['Mint'], ['Mustard'], ['Olive'], ['Orange'], ['Peach'], ['Pear'], ['Pine'], ['Pink'], ['Platinum'], ['Plum'], ['Purple'], ['Red'], ['Rose'], ['Ruby'], ['Rust'], ['Saffron'], ['Sapphire'],  ['Scarlet'], ['Shamrock'], ['Silver'], ['Tan'], ['Tangerine'], ['Teal'], ['Titanium'], ['Turquoise'], ['Vermilion'], ['Violet'], ['Viridian'], ['Wheat'],['White'],['Yellow'],['Zucchini']]
  BRAND = [['Acer'], ['Amazon'], ['Apple'], ['AT&T'], ['Benq'], ['Casio'], ['Fujitsu'], ['HP'], ['Kyocera'], ['LG'], ['Microsoft'], ['Mitsubishi'], ['Motorola'], ['O2'], ['Philips'], ['Samsung'], ['Siemens'], ['Ericsson'], ['Sony'], ['Asus'], ['BlackBerry'], ['Bosch'], ['Dell'], ['Garmin Asus'], ['Haier'], ['HTC'], ['Lenovo'], ['Micromax'], ['Nokia'], ['Orange'], ['Panasonic'], ['Sharp'], ['T Mobile'], ['Toshiba'], ['Vodafone']]
  scope :available, where('available = ?', true)
  scope :for_user, lambda{|user_id| where("user_id = ?", user_id)}
  scope :chronological, order('listing_date DESC')
  scope :latest, lambda{|num| limit(num).order('listing_date DESC')}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @title = "Online Store"
    products_list = Product.all.map{|product| product}
    list = []
    products_list.each do|product|
      if product.available? || product.user_id == session[:user_id]
        if product.expiry_date > Date.today || product.user_id == session[:user_id]
          list << product
        end
      end
    end
    @products = list

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @title = "Your Product"
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @title = "Register Product"
    @product = current_user.products.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @title = "Edit Product"
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.select(:color, Product::KULER) %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.select(:brand, Product::BRAND) %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :fragile %><br />
    <%= f.check_box :fragile %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :listing_date %><br />
    <%= f.date_select :listing_date %>
  </div>
  <div class="field">
    <%= f.label :expiry_date %><br />
    <%= f.date_select :expiry_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table id="Product List">
  <tr>
    
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Color</th>
    <th>Brand</th>
    <th>Fragile</th>
    <th>Available</th>
  
    <th>Expiry date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.description %></td>
    <td><%= product.color %></td>
    <td><%= product.brand %></td>
    <td><%= product.fragile %></td>
    <td><%= product.available %></td>
 
    <td><%= product.expiry_date %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @product.user.proper_name %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<% unless @product.photo_url.nil? %>
  <p><%= image_tag @product.photo_url %></p>
<% end %>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Color:</b>
  <%= @product.color %>
</p>

<p>
  <b>Brand:</b>
  <%= @product.brand %>
</p>

<p>
  <b>Fragile:</b>
  <%= @product.fragile %>
</p>

<p>
  <b>Available:</b>
  <%= @product.available %>
</p>

<p>
  <b>Listing date:</b>
  <%= @product.listing_date %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @product.expiry_date %>
</p>


<%= button_to 'Purchase', buy_path(@product), class: "btn btn-large btn-primary" %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>